### PR TITLE
[detekt] Load default configuration on detekt config file missing.

### LINKED ISSUE #179: Detekt fails when no config file provided
When `detekt.config.file` is empty processor fails with exception:

```
at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
at pl.touk.sputnik.processor.detekt.DetektProcessor.buildDetector(DetektProcessor.java:73)
at pl.touk.sputnik.processor.detekt.DetektProcessor.process(DetektProcessor.java:46)
at pl.touk.sputnik.engine.ReviewRunner.review(ReviewRunner.java:25)
at pl.touk.sputnik.engine.Engine.run(Engine.java:40)
at pl.touk.sputnik.Main.main(Main.java:36)
```

I think we can use Detekt's default `ProcessingSettings` when missing config

### PR DESCRIPTION
**Pull request by pjagielski**
Resolves #179

### CODE REVIEW

File: src/main/java/pl/touk/sputnik/processor/detekt/DetektProcessor.java [hunk 1]
```diff
@@ -70,13 +71,24 @@ private String buildCommonPathAsFilePrefix(String commonPath) {
 
     @NotNull
     private Detektor buildDetector(String commonPath) {
-        Path configPath = FileSystems.getDefault().getPath(configuration.getProperty(GeneralOption.DETEKT_CONFIG_FILE));
-        Config config = YamlConfig.Companion.load(configPath);
+        String configFilename = configuration.getProperty(GeneralOption.DETEKT_CONFIG_FILE);
```
Comment (sputnikci) [inline src/main/java/pl/touk/sputnik/processor/detekt/DetektProcessor.java]: \[Checkstyle\] ERROR: Line is longer than 80 characters \(found 92\)\.

File: src/main/java/pl/touk/sputnik/processor/detekt/DetektProcessor.java [hunk 2]
```diff
@@ -70,13 +71,24 @@ private String buildCommonPathAsFilePrefix(String commonPath) {
...
+            config = YamlConfig.Companion.load(configPath);
+        } else {
+            config = loadDefaultConfig();
+        }
         ProcessingSettings processingSettings = new ProcessingSettings(FileSystems.getDefault().getPath(commonPath), config, new ArrayList<PathFilter>(), false, false, new ArrayList<Path>());
 
         return DetektFacade.INSTANCE.instance(processingSettings, new RuleSetLocator(processingSettings).load(), Arrays.asList(new LoggingFileProcessor()));
     }
 
+    @NotNull
```
Comment (sputnikci) [inline src/main/java/pl/touk/sputnik/processor/detekt/DetektProcessor.java]: \[Checkstyle\] ERROR: Missing a Javadoc comment\.

File: src/main/java/pl/touk/sputnik/processor/detekt/DetektProcessor.java [hunk 3]
```diff
@@ -70,13 +71,24 @@ private String buildCommonPathAsFilePrefix(String commonPath) {
...
+    private Config loadDefaultConfig() {
+        return YamlConfig.Companion.loadResource(new ClasspathResourceConverter().convert("default-detekt-config.yml"));
```
Comment (sputnikci) [inline src/main/java/pl/touk/sputnik/processor/detekt/DetektProcessor.java]: \[Checkstyle\] ERROR: Line is longer than 80 characters \(found 120\)\.

File: src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java [hunk 4]
```diff
@@ -17,7 +17,8 @@
 import static org.assertj.core.api.Assertions.assertThat;
 
 public class DetektProcessorTest {
-    private static final String CONFIGURATION_WITH_KTLINT_ENABLED = "detekt/configuration/configurationWithEnabledDetekt.properties";
+    private static final String CONFIGURATION_WITH_KTLINT_ENABLED_AND_WITH_DETEKT_CONFIG_FILE = "detekt/configuration/configurationWithEnabledDetektAndDetektConfigFile.properties";
```
Comment (sputnikci) [inline src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java]: \[Checkstyle\] ERROR: Line is longer than 80 characters \(found 180\)\.

Comment (sputnikci) [inline src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java]: \[Checkstyle\] ERROR: Missing a Javadoc comment\.

File: src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java [hunk 5]
```diff
@@ -17,7 +17,8 @@
...
+    private static final String CONFIGURATION_WITH_KTLINT_ENABLED_AND_WITHOUT_DETEKT_CONFIG_FILE = "detekt/configuration/configurationWithEnabledDetektAndWithoutDetektConfigFile.properties";
```
Comment (sputnikci) [inline src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java]: \[Checkstyle\] ERROR: Line is longer than 80 characters \(found 190\)\.

Comment (sputnikci) [inline src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java]: \[Checkstyle\] ERROR: Missing a Javadoc comment\.

File: src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java [hunk 6]
```diff
@@ -29,7 +30,7 @@
 
     @Before
     public void setUp() throws Exception {
-        config = ConfigurationBuilder.initFromResource(CONFIGURATION_WITH_KTLINT_ENABLED);
+        config = ConfigurationBuilder.initFromResource(CONFIGURATION_WITH_KTLINT_ENABLED_AND_WITH_DETEKT_CONFIG_FILE);
```
Comment (sputnikci) [inline src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java]: \[Checkstyle\] ERROR: Line is longer than 80 characters \(found 118\)\.

File: src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java [hunk 7]
```diff
@@ -87,6 +88,18 @@ public void shouldReturnNoViolationsForEmptyReview() {
         assertThat(result.getViolations()).isEmpty();
     }
 
+    @Test
```
Comment (sputnikci) [inline src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java]: \[Checkstyle\] ERROR: Method 'shouldProcessReviewsOnDefaultConfig' is not designed for extension \- needs to be abstract, final or empty\.

Comment (sputnikci) [inline src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java]: \[Checkstyle\] ERROR: Missing a Javadoc comment\.

File: src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java [hunk 8]
```diff
@@ -87,6 +88,18 @@ public void shouldReturnNoViolationsForEmptyReview() {
...
+    public void shouldProcessReviewsOnDefaultConfig() {
+        Configuration configWithoutDetektConfigFile =
+                ConfigurationBuilder.initFromResource(CONFIGURATION_WITH_KTLINT_ENABLED_AND_WITHOUT_DETEKT_CONFIG_FILE);
```
Comment (sputnikci) [inline src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java]: \[Checkstyle\] ERROR: Line is longer than 80 characters \(found 120\)\.

File: src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java [hunk 9]
```diff
@@ -87,6 +88,18 @@ public void shouldReturnNoViolationsForEmptyReview() {
...
+        Review review = getReview(VIOLATIONS_1, VIOLATIONS_2, VIOLATIONS_3, REVIEW_GROOVY_FILE);
```
Comment (sputnikci) [inline src/test/java/pl/touk/sputnik/processor/detekt/DetektProcessorTest.java]: \[Checkstyle\] ERROR: Line is longer than 80 characters \(found 96\)\.
